# Generated by Django 5.1.2 on 2024-11-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file_date', models.DateTimeField()),
                ('po_number', models.CharField(max_length=20)),
                ('po_date', models.DateTimeField()),
                ('dist_channel', models.CharField(choices=[('DA', 'DA'), ('DC', 'DC'), ('DR', 'DR')], max_length=2)),
                ('so_number', models.CharField(max_length=20)),
                ('so_date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sap_info', models.CharField(blank=True, max_length=100)),
                ('jadwal_tgl', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
