# Generated by Django 5.1.2 on 2024-11-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='jadwal_tgl',
            new_name='jadwal_toko',
        ),
    ]
